collections <- switch(
  Sys.getenv("FINBIF_PRIVATE_API"),
  dev = list(
    cit_sci_projects = c(
      "Bird Feeder Monitoring" = "HR.60",
      "Bird Ringing" = "HR.48",
      "Breeding Bird Survey (Points)" = "HR.157",
      "Breeding Bird Survey (Transects)" = "HR.61",
      "Winter Bird Survey" = "HR.39",
      "Bird Atlas 2022–2025 (BirdLife Finland)" = "HR.4412",
      "Bird Atlas 2022–2025 (FinBIF)" = "HR.4471",
      "eBird" = "HR.3691",
      "National Butterfly Monitoring" = "HR.175",
      "Glowworm Monitoring" = "HR.3531",
      "Fungi Atlas" = "HR.2129",
      "Open Observations (Invasives)" = "HR.435",
      "Finvasive" = "HR.3051",
      "Dairy Farm Monitoring" = "HR.3071",
      "FinBIF Notebook" = "HR.1747",
      "Hatikka" = "HR.447",
      "iNaturalist Finland" = "HR.3211",
      "Open Observations" = "HR.203",
      "Retkikasvio" = "HR.4091",
      "School Collection Contest" = "HR.2629",
      "Spring Monitoring" = "HR.206"
    ),
    sources = c(
      "FinBIF" = "HR.1989",
      "Kieppi, Kokkola Museum" = "HR.121",
      "Kuopio Museum" = "HR.1127",
      "Luke" = "HR.1915",
      "Luomus" = "HR.128",
      "Metsähallitus" = "HR.3551",
      "SYKE" = "HR.3552",
      "University of Jyväskylä" = "HR.1247",
      "University of Oulu" = "HR.1207",
      "University of Turku" = "HR.1627"
    ),
    institutions = c(
      "Ark Nature Centre" = "HR.1587",
      "Forssa Museum" = "HR.217",
      "Kieppi, Kokkola Museum" = "HR.121",
      "Kuopio Museum" = "HR.1127",
      "Luomus" = "HR.128",
      "Museum of Lapland" = "HR.2249",
      "Nairobi National Museum" = "HR.3133",
      "Ostrobothnian Museum" = "HR.1727",
      "University of Jyväskylä" = "HR.1247",
      "University of Oulu" = "HR.1207",
      "University of Turku" = "HR.1627"
    )
  ),
  list(
    cit_sci_projects = c(
      "Bird Feeder Monitoring" = "HR.60",
      "Bird Ringing" = "HR.48",
      "Breeding Bird Survey (Points)" = "HR.157",
      "Breeding Bird Survey (Transects)" = "HR.61",
      "Winter Bird Survey" = "HR.39",
      "Bird Atlas 2022–2025 (BirdLife Finland)" = "HR.4412",
      "Bird Atlas 2022–2025 (FinBIF)" = "HR.4471",
      "eBird" = "HR.3691",
      "National Butterfly Monitoring" = "HR.175",
      "Glowworm Monitoring" = "HR.3531",
      "Fungi Atlas" = "HR.2129",
      "Invasives Portal" = "HR.3791",
      "Open Observations (Invasives)" = "HR.435",
      "Pori Estuary Invasives" = "HR.4631",
      "Finvasive" = "HR.3051",
      "Dairy Farm Monitoring" = "HR.3071",
      "FinBIF Notebook" = "HR.1747",
      "Hatikka" = "HR.447",
      "iNaturalist Finland" = "HR.3211",
      "Open Observations" = "HR.203",
      "Retkikasvio" = "HR.4091",
      "School Collection Contest" = "HR.2629",
      "Spring Monitoring" = "HR.206"
    ),
    sources = c(
      "FinBIF" = "HR.1989",
      "Iisalmi Museum" = "HR.4911",
      "Kieppi, Kokkola Museum" = "HR.121",
      "Kuopio Museum" = "HR.1127",
      "Luke" = "HR.1915",
      "Luomus" = "HR.128",
      "Metsähallitus" = "HR.3551",
      "Porvoo Museum" = "HR.4171",
      "SYKE" = "HR.3552",
      "Tampere Museum" = "HR.3811",
      "University of Jyväskylä" = "HR.1247",
      "University of Oulu" = "HR.1207",
      "University of Turku" = "HR.1627"
    ),
    institutions = c(
      "Ark Nature Centre" = "HR.1587",
      "Forssa Museum" = "HR.217",
      "Iisalmi Museum" = "HR.4911",
      "Kieppi, Kokkola Museum" = "HR.121",
      "Kuopio Museum" = "HR.1127",
      "Luomus" = "HR.128",
      "Museum of Lapland" = "HR.2249",
      "Nairobi National Museum" = "HR.3133",
      "Ostrobothnian Museum" = "HR.1727",
      "Porvoo Museum" = "HR.4171",
      "Tampere Museum" = "HR.3811",
      "University of Jyväskylä" = "HR.1247",
      "University of Oulu" = "HR.1207",
      "University of Turku" = "HR.1627"
    )
  )
)
