---
title: "LAJI.FI"
output: 
  flexdashboard::flex_dashboard:
    favicon: favicon.ico
    theme:
      version: 5
      fg: "#FDF7F7"
      bg: "#2C3E50"
      primary: "#2691D9"
      base_font:
        google: Roboto
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
runtime: shiny_prerendered
---

```{js, echo = FALSE}
document.querySelector(".navbar-header").innerHTML =
  '<a href="https://laji.fi" class="navbar-brand">LAJI.FI</a>'
```

```{r setup, context = "setup", include = FALSE}
library(DT)
library(dplyr)
library(flexdashboard)
library(future)
library(geofi)
library(ggplot2)
library(httr2)
library(lubridate)
library(plotly)
library(promises)
library(scales)
library(shinyjs)
library(sf)
library(thematic)
library(waiter)

plan(multisession)

thematic_shiny(
  font = "Roboto", fg = "#FDF7F7", bg = "#2C3E50", accent = "#2691D9"
)

api <- Sys.getenv("DASHBOARD_API")

req <- request(api)

finland <- get_municipalities()

bio_province_zip <- "FI_FMNH_BGR_20161118.zip"

url <- "https://cdn.laji.fi/files/biogeographical-province/%s"

url <- sprintf(url, bio_province_zip)

download.file(url, bio_province_zip)

unzip(bio_province_zip, "FI_FMNH_BGR_20161118_3067.gml")

bio_provinces <- st_read("FI_FMNH_BGR_20161118_3067.gml")
```

```{r shinyjs, context = "render", echo = FALSE}
addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```

```{r resources, context = "server"}
useShinyjs(html = TRUE)
```

<script src="shinyjs/inject.js"></script>

```{r waiter, context = "render", echo = FALSE}
addResourcePath("robots.txt", "robots.txt")
addResourcePath("favicon.ico", "favicon.ico")
autoWaiter(
  html = spin_ring(),
  color = "transparent",
  fadeout = TRUE
)
```

Occurrence Data
================================================================================

Column {data-width=150}
--------------------------------------------------------------------------------

### {data-height=250}

####

```{r sources, context = "render", echo = FALSE}
selectInput(
  "source",
  NULL,
  c(
    "Data Source   " = "",
    "All Sources" = "NULL",
    "FinBIF" = "HR.1989",
    "Iisalmi Museum" = "HR.4911",
    "Kieppi, Kokkola Museum" = "HR.121",
    "Kuopio Museum" = "HR.1127",
    "Luke" = "HR.1915",
    "Luomus" = "HR.128",
    "Metsähallitus" = "HR.3551",
    "Porvoo Museum" = "HR.4171",
    "SYKE" = "HR.3552",
    "Tampere Museum" = "HR.3811",
    "University of Jyväskylä " = "HR.1247",
    "University of Oulu" = "HR.1207",
    "University of Turku" = "HR.1627"
  ),
  width = "100%"
)
selectInput(
  "taxa",
  NULL,
  c(
    "Taxa   " = "",
    "All Taxa" = "NULL",
    "Algae" = "Algae",
    "Bryophytes" = "Bryophytes",
    "Vascular Plants"= "Vascular Plants",
    "Fungi & Lichen" = "Fungi and lichens",
    "Worms" = "Worms",
    "Molluscs" = "Molluscs",
    "Crustaceans" = "Crustaceans",
    "Myriapods" = "Myriapods",
    "Insects & Arachnids" = "Insects and arachnids",
    "Fish" = "Fishes",
    "Reptiles & Amphibians" = "Reptiles and amphibians",
    "Birds" = "Birds",
    "Mammals" = "Mammals"
  ),
  width = "100%"
)
selectInput(
  "restriction",
  NULL,
  c(
    "Data Restriction   " = "",
    "All Data" = "NULL",
    "Restricted Only" = "true",
    "Unrestricted Only" = "false"
  ),
  width = "100%"
)
```

####

```{r reset1, context = "render", echo = FALSE}
actionButton("reset1", "Reset", width = "100%", class = "btn-primary")
```

```{r reset_render1, context = "server"}
observeEvent(
  input$reset1,
  {
    reset("source")
    reset("taxa")
    reset("restriction")
    reset("collection_quality")
    reset("level")
  }
)
```

Column {data-width=200}
--------------------------------------------------------------------------------

### Records

```{r fb_record_count_output, context = "render", echo = FALSE}
valueBoxOutput("record_count")
```

```{r fb_record_count_render, context = "server"}
record_count <-
  reactive({

    req <-
      req_url_path(req, "record-count") |>
      req_url_query(
        restriction = input$restriction,
        taxa = input$taxa,
        source = input$source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      valueBox(icon = "fa-pen", color = "#2691D9")

    }, seed = TRUE)

  }) |>
  bindCache(input$restriction, input$taxa, input$source, cache = "session") |>
  bindEvent(input$restriction, input$taxa, input$source)

output$record_count <- renderValueBox(record_count())
```

### Species

```{r fb_species_count_output, context = "render", echo = FALSE}
valueBoxOutput("species_count")
```

```{r fb_species_count_render, context = "server"}
species_count <-
  reactive({

    req <-
      req_url_path(req, "species-count") |>
      req_url_query(
        restriction = input$restriction,
        taxa = input$taxa, 
        source = input$source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      valueBox(icon = "fa-dove", color = "#2691D9")

    }, seed = TRUE)

  }) |>
  bindCache(input$restriction, input$taxa, input$source, cache = "session") |>
  bindEvent(input$restriction, input$taxa, input$source)

output$species_count <- renderValueBox(species_count())
```

### Datasets

```{r fb_collection_count_output, context = "render", echo = FALSE}
valueBoxOutput("collection_count")
```

```{r fb_collection_count_render, context = "server"}
collection_count <-
  reactive({

    req <-
      req_url_path(req, "collection-count") |>
      req_url_query(
        restriction = input$restriction,
        taxa = input$taxa, 
        source = input$source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      valueBox(icon = "fa-database", color = "#2691D9")

    }, seed = TRUE)

  }) |>
  bindCache(input$restriction, input$taxa, input$source, cache = "session") |>
  bindEvent(input$restriction, input$taxa, input$source)

output$collection_count <- renderValueBox(collection_count())
```

###

```{r quality_table_output, context = "render", echo = FALSE}
selectInput(
  "collection_quality",
  NULL,
  c(
    "Dataset Quality Level   " = "",
    "All Levels" = "NULL",
    "Professionals" = "professional",
    "Specialists" = "hobbyist",
    "Citizen Scientists" = "amateur"
  ),
  width = "100%"
)

dataTableOutput("quality_table")
```

```{r quality_table_render, context = "server"}
quality_table <-
  reactive({

    req <-
      req_url_path(req, "quality-table") |>
      req_url_query(
        collection_quality = input$collection_quality,
        restriction = input$restriction,
        taxa = input$taxa, 
        source = input$source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize()

    }, seed = TRUE)

  }) |>
  bindCache(
    input$collection_quality, input$restriction, input$taxa, input$source,
    cache = "session"
  ) |>
  bindEvent(
    input$collection_quality, input$restriction, input$taxa, input$source
  )

output$quality_table <- renderDataTable({

  quality_table() %...>%
  datatable(
    rownames = FALSE,
    options = list(
      bPaginate = FALSE,
      searching = FALSE,
      info = FALSE,
      ordering = FALSE,
      processing = FALSE
    ),
    fillContainer = TRUE
  )

})
```

Column {data-width=250 .tabset .tabset-fade}
--------------------------------------------------------------------------------

### Occurrences

```{r occurrence_plot_output, context = "render", echo = FALSE}
plotlyOutput("occurrence_plot")
```

```{r occurrence_plot_render, context = "server"}
occurrence_plot <-
  reactive({

    req <-
      req_url_path(req, "occurrence-plot") |>
      req_url_query(
        restriction = input$restriction,
        taxa = input$taxa, 
        source = input$source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      mutate(Date = as_date(Date)) |>
      ggplot() +
        aes(x = Date, y = Records) +
        geom_line() +
        facet_wrap(~Type, 2) +
        scale_y_continuous(label = comma) +
        labs(x = NULL, y = NULL) +
        theme(plot.margin = unit(c(20, 0, 0, 10), "points"))

    }, seed = TRUE)

  }) |>
  bindCache(input$restriction, input$taxa, input$source, cache = "session") |>
  bindEvent(input$restriction, input$taxa, input$source)

output$occurrence_plot <- renderPlotly({

  occurrence_plot() %...>%
  ggplotly(dynamicTicks = TRUE)

})
```

### Annotations

```{r annotations_plot_output, context = "render", echo = FALSE}
plotlyOutput("annotations_plot")
```

```{r annotations_plot_render, context = "server"}
annotations_plot <-
  reactive({

    req <-
      req_url_path(req, "annotations-plot") |>
      req_url_query(
        restriction = input$restriction,
        taxa = input$taxa, 
        source = input$source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      mutate(Date = as_date(Date)) |>
      ggplot() +
        aes(x = Date, y = Annotations) +
        geom_line() +
        scale_y_continuous(label = comma) +
        labs(x = NULL, y = NULL)

    }, seed = TRUE)

  }) |>
  bindCache(input$restriction, input$taxa, input$source, cache = "session") |>
  bindEvent(input$restriction, input$taxa, input$source)

output$annotations_plot <- renderPlotly(

  annotations_plot() %...>%
  ggplotly(dynamicTicks = TRUE)

)
```

Column {data-width=300}
--------------------------------------------------------------------------------

### 

```{r municipality_map_output, context = "render", echo = FALSE}
fillCol(
  height = "100%",
  flex = c(NA, 1),
  selectInput(
    "level",
    NULL,
    c(
      "Region" = "maakunta_name_fi",
      "Biogeographical Province" = "MAAKUNTA_FI",
      "Municipality" = "municipality_name_fi"
    ),
    width = "100%"
  ),
  plotlyOutput("municipality_map")
)
```

```{r municipality_map_render, context = "server"}
municipality_map <-
  reactive({

    level <- input$level

    endpoint <- switch(
      level, MAAKUNTA_FI = "bio-province-map", "municipality-map"
    )

    req <-
      req_url_path(req, endpoint) |>
      req_url_query(
        restriction = input$restriction,
        taxa = input$taxa, 
        source = input$source
      )

    future_promise({

      n <-
        req_perform(req) |>
        resp_body_raw() |>
        unserialize()

      map_data <-
        switch(
          level,
          MAAKUNTA_FI = left_join(bio_provinces, n, by = join_by(MAAKUNTA_FI)),
          left_join(finland, n, by = join_by(municipality_name_fi))
        )

      group_by(map_data, .data[[level]]) |>
      summarise(Records = sum(n_records, na.rm = TRUE)) |>
      mutate(
        text = paste0(.data[[level]], ": " , Records),
      ) |>
      st_cast("MULTIPOLYGON") |>
      ggplot() +
        aes(fill = Records, text = text) +
        geom_sf() +
        scale_fill_viridis_c(label = comma)

    }, seed = TRUE)

  }) |>
  bindCache(
    input$level, input$restriction, input$taxa, input$source, cache = "session"
  ) |>
  bindEvent(input$level, input$restriction, input$taxa, input$source)

output$municipality_map <- renderPlotly({

  municipality_map() %...>%
  ggplotly(tooltip = "text")

})
```

Specimen Collections/Digitisation
================================================================================

Column {data-width=150}
--------------------------------------------------------------------------------

### {data-height=250}

####

```{r spec_sources, context = "render", echo = FALSE}
selectInput(
  "spec_source",
  NULL,
  c(
    "Institution   " = "",
    "All Institutions" = "NULL",
    "Ark Nature Centre" = "HR.1587",
    "Forssa Museum" = "HR.217",
    "Iisalmi Museum" = "HR.4911",
    "Kieppi, Kokkola Museum" = "HR.121",
    "Kuopio Museum" = "HR.1127",
    "Luomus" = "HR.128",
    "Museum of Lapland" = "HR.2249",
    "Nairobi National Museum" = "HR.3133",
    "Ostrobothnian Museum" = "HR.1727",
    "Porvoo Museum" = "HR.4171",
    "Tampere Museum" = "HR.3811",
    "University of Jyväskylä " = "HR.1247",
    "University of Oulu" = "HR.1207",
    "University of Turku" = "HR.1627"
  ),
  width = "100%"
)
selectInput(
  "discipline",
  NULL,
  c(
    "Discipline   " = "",
    "All Disciplines" = "NULL",
    "Botany" = "is_botany",
    "Zoology" = "is_zoology",
    "Geology" = "is_geology"
  ),
  width = "100%"
)
```

####

```{r reset2, context = "render", echo = FALSE}
actionButton("reset2", "Reset", width = "100%", class = "btn-primary")
```

```{r reset_render2, context = "server"}
observeEvent(
  input$reset2,
  {
    reset("spec_source")
    reset("discipline")
  }
)
```


Column {data-width=200}
--------------------------------------------------------------------------------

### Specimens

```{r fb_specimen_count_output, context = "render", echo = FALSE}
valueBoxOutput("specimen_count")
```

```{r fb_specimen_count_render, context = "server"}
specimen_count <-
  reactive({

    req <-
      req_url_path(req, "specimen-collections") |>
      req_url_query(
        discipline = input$discipline,
        spec_source = input$spec_source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      valueBox(icon = "fa-mosquito", color = "#2691D9")

    }, seed = TRUE)

  }) |>
  bindCache(input$discipline, input$spec_source, cache = "session") |>
  bindEvent(input$discipline, input$spec_source)

output$specimen_count <- renderValueBox(specimen_count())
```

### Digitised

```{r fb_digitised_count_output, context = "render", echo = FALSE}
valueBoxOutput("digitised_count")
```

```{r fb_digitised_count_render, context = "server"}
digitised_count <-
  reactive({

    req <-
      req_url_path(req, "specimen-collections") |>
      req_url_query(
        discipline = input$discipline,
        spec_source = input$spec_source,
        stat = "n_specimens_digitised"
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      valueBox(icon = "fa-computer", color = "#2691D9")

    }, seed = TRUE)

  }) |>
  bindCache(input$discipline, input$spec_source, cache = "session") |>
  bindEvent(input$discipline, input$spec_source)

output$digitised_count <- renderValueBox(digitised_count())
```

### Percent Digitised

```{r fb_digitised_percent_output, context = "render", echo = FALSE}
gaugeOutput("digitised_percent")
```

```{r fb_digitised_percent_render, context = "server"}
digitised_percent <-
  reactive({

    req <-
      req_url_path(req, "specimen-collections") |>
      req_url_query(
        discipline = input$discipline,
        spec_source = input$spec_source,
        stat = "percent_digitised"
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      gauge(min = 0, max = 100, symbol = "%")

    }, seed = TRUE)

  }) |>
  bindCache(input$discipline, input$spec_source, cache = "session") |>
  bindEvent(input$discipline, input$spec_source)

output$digitised_percent <- renderGauge(digitised_percent())
```

### Imaged

```{r fb_imaged_count_output, context = "render", echo = FALSE}
valueBoxOutput("imaged_count")
```

```{r fb_imaged_count_render, context = "server"}
imaged_count <-
  reactive({

    req <-
      req_url_path(req, "specimen-collections") |>
      req_url_query(
        discipline = input$discipline,
        spec_source = input$spec_source,
        stat = "n_specimens_imaged"
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      valueBox(icon = "fa-camera", color = "#2691D9")

    }, seed = TRUE)

  }) |>
  bindCache(input$discipline, input$spec_source, cache = "session") |>
  bindEvent(input$discipline, input$spec_source)

output$imaged_count <- renderValueBox(imaged_count())
```

### Percent Imaged

```{r fb_imaged_percent_output, context = "render", echo = FALSE}
gaugeOutput("imaged_percent")
```

```{r fb_imaged_percent_render, context = "server"}
imaged_percent <-
  reactive({

    req <-
      req_url_path(req, "specimen-collections") |>
      req_url_query(
        discipline = input$discipline,
        spec_source = input$spec_source,
        stat = "percent_imaged"
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      gauge(min = 0, max = 100, symbol = "%")

    }, seed = TRUE)

  }) |>
  bindCache(input$discipline, input$spec_source, cache = "session") |>
  bindEvent(input$discipline, input$spec_source)

output$imaged_percent <- renderGauge(imaged_percent())
```

Column {data-width=550 .tabset .tabset-fade}
--------------------------------------------------------------------------------

### Collections

```{r collection_plot_output, context = "render", echo = FALSE}
plotlyOutput("collection_plot")
```

```{r collection_plot_render, context = "server"}
collection_plot <-
  reactive({

    req <-
      req_url_path(req, "specimen-collections") |>
      req_url_query(
        discipline = input$discipline,
        spec_source = input$spec_source,
        stat = "table"
      )
    
    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      ggplot() +
        aes(Collection, n, fill = Status) +
        geom_bar(stat = "identity") +
        coord_flip() +
        scale_fill_viridis_d() +
        labs(x = NULL, y = NULL)

    }, seed = TRUE)

  }) |>
  bindCache(input$discipline, input$spec_source, cache = "session") |>
  bindEvent(input$discipline, input$spec_source)

output$collection_plot <- renderPlotly({

  collection_plot() %...>%
  ggplotly(dynamicTicks = TRUE) %...>%
  layout(
    legend = list(
      x = 0, xanchor = "left", yanchor = "bottom", orientation = "h"
    )
  )

})
```

### Progress

```{r progress_plot_output, context = "render", echo = FALSE}
plotlyOutput("progress_plot")
```

```{r progress_plot_render, context = "server"}
progress_plot <-
  reactive({

    req <-
      req_url_path(req, "progress-plot") |>
      req_url_query(
        discipline = input$discipline,
        spec_source = input$spec_source
      )

    future_promise({

      req_perform(req) |>
      resp_body_raw() |>
      unserialize() |>
      mutate(Date = as_date(Date)) |>
      ggplot() +
        aes(x = Date, y = Specimens) +
        geom_line() +
        facet_wrap(~Status, 2) +
        scale_y_continuous(label = comma) +
        labs(x = NULL, y = NULL) +
        theme(plot.margin = unit(c(20, 0, 0, 10), "points"))

    }, seed = TRUE)

  }) |>
  bindCache(input$discipline, input$spec_source, cache = "session") |>
  bindEvent(input$discipline, input$spec_source)

output$progress_plot <- renderPlotly({

  progress_plot() %...>%
  ggplotly(dynamicTicks = TRUE)

})
```
