kind: Template
apiVersion: v1
parameters:
  - name: BRANCH
    required: true
  - name: APP
    required: true
    value: finbif-dashboard
  - name: API
    required: true
    value: plumber
  - name: GIT_HOST
    required: true
    value: https://github.com
  - name: ORG
    required: true
    value: luomus
  - name: TAG
    required: true
    value: latest
  - name: APP_PORT
    required: true
    value: "3838"
  - name: API_PORT
    required: true
    value: "8000"
  - name: APP_CMD
    required: true
    value: '["R", "-e", "rmarkdown::run(\"index.Rmd\", shiny_args = list(port = 3838, host = \"0.0.0.0\"))"]'
  - name: API_CMD
    required: true
    value: '["Rscript", "--vanilla", "init.R"]'
  - name: FINBIF_PRIVATE_API
    required: true
  - name: HOST
    required: true
  - name: GITHUB_SECRET
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{64}"
metadata:
  name: ${APP}
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP}-${BRANCH}:${TAG}
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${APP}.git
        ref: ${BRANCH}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${BRANCH}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${APP}-${BRANCH}
      spec:
        containers:
        - image: ${APP}-${BRANCH}:${TAG}
          name: ${APP}-${BRANCH}
          command: ${{APP_CMD}}
          env:
          - name: DASHBOARD_API
            value: ${API}-${BRANCH}:${API_PORT}
          ports:
          - containerPort: ${APP_PORT}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}-${BRANCH}
        from:
          kind: ImageStreamTag
          name: ${APP}-${BRANCH}:${TAG}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${API}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${API}-${BRANCH}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${API}-${BRANCH}
      spec:
        containers:
        - image: ${APP}-${BRANCH}:${TAG}
          name: ${API}-${BRANCH}
          command: ${{API_CMD}}
          env:
          - name: FINBIF_PRIVATE_API
            value: ${FINBIF_PRIVATE_API}
          ports:
          - containerPort: ${API_PORT}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${API}-${BRANCH}
        from:
          kind: ImageStreamTag
          name: ${APP}-${BRANCH}:${TAG}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}
      port: ${APP_PORT}
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${BRANCH}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${API}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${API_PORT}
      port: ${API_PORT}
      targetPort: ${{API_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${API}-${BRANCH}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    host: ${HOST}
    port:
      targetPort: ${APP_PORT}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP}-${BRANCH}
    wildcardPolicy: None
